stages:
  - build
  - push
  - deploy

variables:
  PROJECT_NAME: project-argian
  REPO_NAME: webapp-1

image: docker:latest

docker-build:
  stage: build
  script:
    - docker info
    - docker build -t ${CI_REGISTRY_URL}:8087/${PROJECT_NAME}/${REPO_NAME}:$CI_COMMIT_SHORT_SHA .
  only:
    - main

docker-push:
  stage: push
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY_URL}:8087
    - docker push ${CI_REGISTRY_URL}:8087/${PROJECT_NAME}/${REPO_NAME}:$CI_COMMIT_SHORT_SHA
  only:
    - main

